// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/dstdfx/twbridge/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// EventsHandler is an autogenerated mock type for the EventsHandler type
type EventsHandler struct {
	mock.Mock
}

// HandleHelpEvent provides a mock function with given fields: event
func (_m *EventsHandler) HandleHelpEvent(event *domain.HelpEvent) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.HelpEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleLoginEvent provides a mock function with given fields: _a0
func (_m *EventsHandler) HandleLoginEvent(_a0 *domain.LoginEvent) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.LoginEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleLogoutEvent provides a mock function with given fields: _a0
func (_m *EventsHandler) HandleLogoutEvent(_a0 *domain.LogoutEvent) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.LogoutEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleRepeatedLoginEvent provides a mock function with given fields: _a0
func (_m *EventsHandler) HandleRepeatedLoginEvent(_a0 *domain.LoginEvent) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.LoginEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleReplyEvent provides a mock function with given fields: _a0
func (_m *EventsHandler) HandleReplyEvent(_a0 *domain.ReplyEvent) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ReplyEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleStartEvent provides a mock function with given fields: _a0
func (_m *EventsHandler) HandleStartEvent(_a0 *domain.StartEvent) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.StartEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleTextMessageEvent provides a mock function with given fields: _a0
func (_m *EventsHandler) HandleTextMessageEvent(_a0 *domain.TextMessageEvent) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.TextMessageEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsLoggedIn provides a mock function with given fields:
func (_m *EventsHandler) IsLoggedIn() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
